### ISSUE TITLE
Uninstall fails

### ISSUE THREAD

**Issue by luke-nehemedia** [boldenamsterdam/htmlcache#41]
How can I uninstall the plugin? I always get an error:

`*** failed to uninstall html-cache: Getting unknown property: bolden\htmlcache\HtmlCache::htmlcacheService`

Since the plugin is not developed anymore, I would like to remove it from the system.

**Comment by scholejo** [comment]
I know this is quite old but I just had the same issue and found out that the `htmlcacheService` Property is only assigned to the `HtmlCache` Class if you're not in Console-Mode. This has the effect that you can only uninstall the plugin from the Control Panel.

Another hint: Ensure that the directory `storage/runtime/htmlcache` exists or otherwise you'll get an exception when attempting to uninstall from the control panel.

Maybe this helps anyone in the future.

**Comment by luke-nehemedia** [comment]
Cannot confirm this. Uninstall was not possible, neither from the CP nor the console. 

After some digging in I found the solution: Rename `records/HtmlCacheCachesRecord.php` into `records/HtmlCacheCache.php` and the uninstall works just fine.
